In [1]:
x = "Hello PJ"
print(x)

Hello PJ


In [2]:
import numpy as np


In [3]:
def NearZero(z):
    return abs(z) < 1e-5
    
# NearZero(1e-6)

In [4]:
def normalize(V):
    V = np.array([1, 2, 3])
    return V/ np.linalg.norm(V)

# normalize([3, 2, 1])

In [5]:
def RotInv(R):
    return (R).T
R = np.array([[1, 2, 3],
              [1, 2, 3],
              [1, 2, 3]])
RotInv(R)

array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

In [6]:
# this is helping in writing the 3x3 matrix from the vector omega
def matrixomg(omg):
    # omg = np.array([1, 2, 3])
    return np.array([[0,     -omg[2],   omg[1]],
                     [omg[2],  0,      -omg[0]],
                     [-omg[1],  omg[0],      0]])

omg = np.array([1, 2, 3])
matrixomg(omg)

array([[ 0, -3,  2],
       [ 3,  0, -1],
       [-2,  1,  0]])

In [7]:
# this will help in writing the vector omega from the 3x3 matrix
def vecomg(matomg):
    return np.array([matomg[2][1], matomg[0][2], matomg[1][0]])

matomg = np.array([[0, -3, 2],
                   [3, 0, -1],
                   [-2, 1, 0]])

vecomg(matomg)

array([1, 2, 3])

In [8]:
# this will give the omega vector and theta 

def omgtheta(value):
    return (normalize(value), np.linalg.norm(value))

value = np.array([1, 2, 3])
omgtheta(value)

(array([0.26726124, 0.53452248, 0.80178373]), np.float64(3.7416573867739413))

In [9]:
#  finding the roation matrix from the omega matrix 

def rotmat(omegamat, theta):    
    return np.array(np.eye(3) + np.sin(theta)*omegamat + (1-np.cos(theta))*np.dot(omegamat, omegamat))

threexthreemat = np.array([[0, -3, 2],
                     [3, 0, -1],
                     [-2, 1, 0]])

vectoromg = vecomg(threexthreemat)
theta = omgtheta(vectoromg)[1]
omegamat = threexthreemat / theta


rotmat(omegamat, theta)

array([[-0.69492056,  0.71352099,  0.08929286],
       [-0.19200697, -0.30378504,  0.93319235],
       [ 0.69297817,  0.6313497 ,  0.34810748]])

In [10]:
import numpy as np
def matrixlog(R):
    import numpy as np;
    acosinput = (np.trace(R)-1) / 2.0
    if acosinput >=1:
        return np.zeros((3, 3))
    elif acosinput <1:
        if not NearZero(1+R[2][2]):
            omg = (1.0 / np.sqrt(2 *(1+R[2][2])) * np.array([R[0][2], R[1][2], 1 + R[2][2]]))
        if not NearZero(1+R[1][1]):
            omg = (1.0 / np.sqrt(2 *(1+R[1][1])) * np.array([R[0][1], 1 + R[1][1], R[2][1]]))
        if not NearZero(1+R[0][0]):
            omg = (1.0 / np.sqrt(2 * (1+R[0][0])) * np.array([1 + R[0][0], R[1][0], R[2][0]]))
        return matrixomg(np.pi * omg )

        
R = np.array([[0, 0, 1],
              [1, 0, 0],
              [0, 1, 0]])
matrixlog(R)



# np.array([[          0, -1.20919958,  1.20919958],
#           [ 1.20919958,           0, -1.20919958],
#           [-1.20919958,  1.20919958,           0]])

array([[ 0.        , -0.        ,  2.22144147],
       [ 0.        ,  0.        , -2.22144147],
       [-2.22144147,  2.22144147,  0.        ]])

In [11]:
# creating the transformation matrix from rotation and position matrix.
def tfmat(Rot, pos):
    return np.r_[np.c_[Rot, pos], [[0, 0, 0, 1]]]      

Rot = np.array([[0, 0, 1],
                [1, 0, 0],
                [0, 1, 0]])

pos = np.array([1, 2, 3])
tfmat(Rot, pos)



# np.c_[Rot, pos]
# This horizontally concatenates the Rot matrix with the pos column vector:

# np.c_[Rot, pos]

# [[R11, R12, R13, px],
#  [R21, R22, R23, py],
#  [R31, R32, R33, pz]]
# ---------------------------------------------------------------
# np.r_[ ..., [[0, 0, 0, 1]] ]
# This vertically stacks the above 3×4 matrix with a row [0, 0, 0, 1]:

# Result:

# [[R11, R12, R13, px],
#  [R21, R22, R23, py],
#  [R31, R32, R33, pz],
#  [  0,   0,   0,  1]]

array([[0, 0, 1, 1],
       [1, 0, 0, 2],
       [0, 1, 0, 3],
       [0, 0, 0, 1]])

In [12]:
def Rotpos(tfmat):
    return tfmat[0:3, 0:3], tfmat[0:3, 3]

tfmat = np.array([[0, 0, 1, 1],
                  [1, 0, 0, 2],
                  [0, 1, 0, 3],
                  [0, 0, 0, 1]])
Rotpos(tfmat)
# Rot, pos = Rotpos(tfmat)


(array([[0, 0, 1],
        [1, 0, 0],
        [0, 1, 0]]),
 array([1, 2, 3]))

In [13]:
# defining the inverse of homogenous transformation matrix 
def Invtfmat(tfmat):
    return np.r_[np.c_[Rotinv, -np.dot(Rotinv,pos)], [[0, 0, 0, 1]]]

tfmat = np.array([[1,  0,  0,  0],
                  [0,  0, -1,  0],
                  [0,  1,  0,  3],
                  [0,  0,  0,  1]])
Rot, pos = Rotpos(tfmat)
Rotinv = np.array(Rot).T
# print(pos)
Invtfmat(tfmat)

array([[ 1,  0,  0,  0],
       [ 0,  0,  1, -3],
       [ 0, -1,  0,  0],
       [ 0,  0,  0,  1]])

In [14]:
# defining the se3 matrix from the 4x4 mat
def vectose3(vec):
    return np.r_[np.c_[matrixomg([vec[0], vec[1], vec[2]]), [vec[3], vec[4], vec[5]]], np.zeros((1,4))]

vec = np.array([1, 2, 3, 4, 5, 6])
vectose3(vec)

array([[ 0., -3.,  2.,  4.],
       [ 3.,  0., -1.,  5.],
       [-2.,  1.,  0.,  6.],
       [ 0.,  0.,  0.,  0.]])

In [15]:
#  defining the 4x4 matrix from se3 matrix
def se3tovec(vecmat):
    return np.array([vecmat[2][1], vecmat[0][2], vecmat[1][0], vecmat[0][3], vecmat[1][3], vecmat[2][3]])

vecmat = np.array([[ 0, -3,  2,  4],
                   [ 3,  0, -1,  5],
                   [-2,  1,  0,  6],
                   [ 0,  0,  0,  0]])

se3tovec(vecmat)

array([1, 2, 3, 4, 5, 6])

In [16]:
# finding the adjoint of the transformation matrix 
def Adj(transmatrix):
    return np.r_[np.c_[Rot, np.zeros((3, 3))], np.c_[np.dot(matrixomg(pos), Rot), Rot]]

transmatrix = np.array([[1,  0,  0,  0],
                        [0,  0, -1,  0],
                        [0,  1,  0,  3],
                        [0,  0,  0,  1]])
Rot, pos = Rotpos(transmatrix)

Adj(transmatrix)


array([[ 1.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0., -1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  3.,  1.,  0.,  0.],
       [ 3.,  0.,  0.,  0.,  0., -1.],
       [ 0.,  0.,  0.,  0.,  1.,  0.]])

In [20]:
def screwaxistovector(q,s,h):
    return np.r_[s, (np.cross(q,s) + np.dot(h,s))]

q = np.array([3,0,0])
s = np.array([0,0,1])
h = 2

screwaxistovector(q,s,h)


array([ 0,  0,  1,  0, -3,  2])

In [39]:
def screwtheta(screwaxis):
    theta1 = np.linalg.norm([screwaxis[0], screwaxis[1], screwaxis[2]])
    
    if NearZero(theta1):
        theta1 = np.linalg.norm([screwaxis[3], screwaxis[4], screwaxis[6]])
    return (np.array(screwaxis/theta1), theta1)

screwaxis = np.array([1,0,0,1,2,3])
# theta1 = np.linalg.norm([screwaxis[0], screwaxis[1], screwaxis[2]])
screwtheta(screwaxis)

(array([1., 0., 0., 1., 2., 3.]), np.float64(1.0))